name: 'Continuous Integration'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install requirements
      run: pip install --upgrade -r requirements.txt

    - name: Update numpy
      run: pip install numpy --upgrade

    - name: Install requirements for tests
      run: pip install --upgrade -r requirements-test.txt

    - name: Run model test
      run: make model-test
      
    - name: Run api test
      run: make api-test